---
abstract: 'Run and test JavaScript code in Perl using Test::More and v8'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JavaScript-V8x-TestMoreish
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  Path::Abstract: 0
  Sub::Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/JavaScript-V8x-TestMoreish/tree/master
version: 0.011
